---
#- include_vars: list.yml
- name: Centos  Add users | create users , shell, home dirs, change password
  user:
    name: '{{item}}'
    password: "{{ 'password' | password_hash('sha512') }}"
    state: present
    comment: created with ansible
    home: /home/{{item}}
    update_password: on_create
  with_items:
    - '{{users}}'
  when: ansible_os_family == "RedHat"

- name: Solaris Add users | create users , shell, home dirs, change password
  user:
    name: '{{item}}'
    password: "{{ 'password' | password_hash('sha512') }}"
    state: present
    comment: created with ansible
    home: /export/home/{{item}}
    update_password: on_create
  with_items:
    - '{{users}}'
  when: ansible_os_family == "Solaris"

- name: Centos Force to change password
  command: "chage -d 0 '{{item}}'"
  with_items:
    - '{{users}}'
  when: ansible_os_family == "RedHat"


- name: Solaris Force to change password
  command: "passwd -f '{{item}}'"
  with_items:
    - '{{users}}'
  when: ansible_os_family == "Solaris"

- name: display users
  command: "cut -d_ -f1 /etc/passwd"
  register: hello

- debug: msg="{{ hello.stdout }}"

- name: ensure the users exist
  user:
   name: '{{item}}'
  with_items:
      - '{{users}}'
