- name: Solaris Add users | create users , shell, home dirs, change password
  user:
    name: '{{user}}'
    password: "{{ 'password' | password_hash('sha512') }}"
    state: present
    comment: created with ansible
    home: /export/home/{{user}}
    update_password: on_create
  register: var_change


- name: Force to change password
  command: "passwd -f '{{item}}'"
  when: var_change.changed